# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Marcos André\Documents\Programas em python\Aplicações Python\Pyqt5 aplicações\Barra_progresso.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(512, 486)
        MainWindow.setStyleSheet("background-color: rgb(47, 134, 181);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(60, 190, 441, 41))
        self.progressBar.setStyleSheet("background-color: rgb(157, 157, 157);")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.zerarB = QtWidgets.QPushButton(self.centralwidget)
        self.zerarB.setGeometry(QtCore.QRect(130, 290, 111, 31))
        self.zerarB.setStyleSheet("background-color: rgb(186, 43, 14);\n"
"font: 75 14pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);")
        self.zerarB.setObjectName("zerarB")
        self.aumentarB = QtWidgets.QPushButton(self.centralwidget)
        self.aumentarB.setGeometry(QtCore.QRect(270, 290, 101, 31))
        self.aumentarB.setStyleSheet("background-color: rgb(65, 197, 0);\n"
"font: 75 14pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);")
        self.aumentarB.setObjectName("aumentarB")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 40, 191, 21))
        self.label.setStyleSheet("font: 75 14pt \"Times New Roman\";\n"
"background-color: rgb(125, 125, 125);\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.zerarB.setText(_translate("MainWindow", "Zerar"))
        self.aumentarB.setText(_translate("MainWindow", "Aumentar"))
        self.label.setText(_translate("MainWindow", "Barra de Progresso"))

if __name__ == "__main__":
        import sys
        valor = 0
        def aumentar():
                global valor
                valor = valor + 10
                ui.progressBar.setValue(valor)
        
        def zerar():
                global valor
                valor = 0
                ui.progressBar.setValue(valor)
        
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        ui.aumentarB.clicked.connect(aumentar)
        ui.zerarB.clicked.connect(zerar)
        MainWindow.show()
        sys.exit(app.exec_())