# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Marcos André\Documents\Programas em python\Aplicações Python\Pyqt5 aplicações\Calendario.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(513, 495)
        MainWindow.setStyleSheet("background-color: rgb(143, 143, 107);\n"
"font: 75 14pt \"Times New Roman\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(30, 60, 461, 281))
        self.calendarWidget.setObjectName("calendarWidget")
        self.dataS = QtWidgets.QLabel(self.centralwidget)
        self.dataS.setGeometry(QtCore.QRect(20, 380, 221, 51))
        self.dataS.setStyleSheet("font: 75 14pt \"Times New Roman\";\n"
"background-color: rgb(126, 126, 126);\n"
"color: rgb(255, 255, 255);")
        self.dataS.setAlignment(QtCore.Qt.AlignCenter)
        self.dataS.setObjectName("dataS")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dataS.setText(_translate("MainWindow", "Data Selecionada : "))

if __name__ == "__main__":
        import sys
        def Data():
             data =  str(ui.calendarWidget.selectedDate())
             dataF = data[19:30]
             ui.dataS.setText("Data selecionada: " + dataF)
        
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        ui.calendarWidget.selectionChanged.connect(Data)
        MainWindow.show()
        sys.exit(app.exec_())