# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Marcos André\Documents\Programas em python\Aplicações Python\Pyqt5 aplicações\List_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(462, 540)
        MainWindow.setStyleSheet("background-color: rgb(0, 190, 190);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(20, 20, 421, 391))
        self.listWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.listWidget.setObjectName("listWidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(80, 420, 291, 31))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.adicionarP = QtWidgets.QPushButton(self.centralwidget)
        self.adicionarP.setGeometry(QtCore.QRect(110, 460, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.adicionarP.setFont(font)
        self.adicionarP.setStyleSheet("background-color: rgb(0, 122, 0);\n"
"color: rgb(255, 255, 255);")
        self.adicionarP.setObjectName("adicionarP")
        self.excluirP = QtWidgets.QPushButton(self.centralwidget)
        self.excluirP.setGeometry(QtCore.QRect(230, 460, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.excluirP.setFont(font)
        self.excluirP.setStyleSheet("background-color: rgb(60, 120, 0);\n"
"color: rgb(255, 255, 255);")
        self.excluirP.setObjectName("excluirP")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.adicionarP.setText(_translate("MainWindow", "Adicionar"))
        self.excluirP.setText(_translate("MainWindow", "Excluir"))


if __name__ == "__main__":
        import sys
        def adicionar():
            if ui.lineEdit.text() != "":
                texto =  ui.lineEdit.text()
                ui.listWidget.addItem(texto)
                ui.lineEdit.setText("")
            else:
                print('Line edit vázia, por favor digite algo')
        
        def excluir():
            ui.listWidget.clear()

        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        ui.adicionarP.clicked.connect(adicionar)
        ui.excluirP.clicked.connect(excluir)
        MainWindow.show()
        sys.exit(app.exec_())
