# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Marcos André\Documents\Programas em python\Aplicações Python\Pyqt5 aplicações\Menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(586, 560)
        MainWindow.setStyleSheet("background-color: rgb(61, 61, 61);")
        MainWindow.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 50, 271, 61))
        self.label.setStyleSheet("font: 75 14pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(107, 107, 107);\n"
"border-color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.CorE = QtWidgets.QLabel(self.centralwidget)
        self.CorE.setGeometry(QtCore.QRect(140, 330, 271, 61))
        self.CorE.setStyleSheet("font: 75 14pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(107, 107, 107);\n"
"border-color: rgb(255, 255, 255);")
        self.CorE.setText("")
        self.CorE.setAlignment(QtCore.Qt.AlignCenter)
        self.CorE.setObjectName("CorE")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 586, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuCores = QtWidgets.QMenu(self.menuBar)
        self.menuCores.setObjectName("menuCores")
        MainWindow.setMenuBar(self.menuBar)
        self.actionVermelho = QtWidgets.QAction(MainWindow)
        self.actionVermelho.setObjectName("actionVermelho")
        self.actionAzul = QtWidgets.QAction(MainWindow)
        self.actionAzul.setObjectName("actionAzul")
        self.actionVerde = QtWidgets.QAction(MainWindow)
        self.actionVerde.setObjectName("actionVerde")
        self.menuCores.addAction(self.actionVermelho)
        self.menuCores.addAction(self.actionAzul)
        self.menuCores.addAction(self.actionVerde)
        self.menuBar.addAction(self.menuCores.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Escolha uma opção do menu"))
        self.menuCores.setTitle(_translate("MainWindow", "Cores"))
        self.actionVermelho.setText(_translate("MainWindow", "Vermelho"))
        self.actionAzul.setText(_translate("MainWindow", "Azul"))
        self.actionVerde.setText(_translate("MainWindow", "Verde"))


if __name__ == "__main__":
        import sys

        def men_vermelho():
                ui.CorE.setText('Vermelho')
                ui.CorE.setStyleSheet("font: 75 14pt \"Times New Roman\";\n"
"color: red;\n"
"background-color: rgb(107, 107, 107);\n"
"border-color: rgb(255, 255, 255);")
        
        def men_verde():
                ui.CorE.setText('Verde')
                ui.CorE.setStyleSheet("font: 75 14pt \"Times New Roman\";\n"
"color: green;\n"
"background-color: rgb(107, 107, 107);\n"
"border-color: rgb(255, 255, 255);")

        def men_azul():
                ui.CorE.setText('Azul')
                ui.CorE.setStyleSheet("font: 75 14pt \"Times New Roman\";\n"
"color: blue;\n"
"background-color: rgb(107, 107, 107);\n"
"border-color: rgb(255, 255, 255);")
                


        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)

        ui.actionVermelho.triggered.connect(men_vermelho)
        ui.actionVerde.triggered.connect(men_verde)
        ui.actionAzul.triggered.connect(men_azul)
        MainWindow.show()
        sys.exit(app.exec_())
