# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Marcos André\Documents\Programas em python\Aplicações Python\Pyqt5 aplicações\Radio_button.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(527, 504)
        MainWindow.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 75 14pt \"Times New Roman\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 70, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(63, 191, 0)")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.cor_escolhida = QtWidgets.QLabel(self.centralwidget)
        self.cor_escolhida.setGeometry(QtCore.QRect(10, 400, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.cor_escolhida.setFont(font)
        self.cor_escolhida.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(63, 191, 0)")
        self.cor_escolhida.setAlignment(QtCore.Qt.AlignCenter)
        self.cor_escolhida.setObjectName("cor_escolhida")
        self.checar = QtWidgets.QPushButton(self.centralwidget)
        self.checar.setGeometry(QtCore.QRect(190, 260, 91, 23))
        self.checar.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(167, 167, 167)")
        self.checar.setObjectName("checar")
        self.vermelho = QtWidgets.QRadioButton(self.centralwidget)
        self.vermelho.setGeometry(QtCore.QRect(190, 110, 121, 17))
        self.vermelho.setStyleSheet("color: rgb(255, 0, 0);")
        self.vermelho.setObjectName("vermelho")
        self.amarelo = QtWidgets.QRadioButton(self.centralwidget)
        self.amarelo.setGeometry(QtCore.QRect(190, 190, 121, 17))
        self.amarelo.setStyleSheet("color: rgb(255, 255, 0);")
        self.amarelo.setObjectName("amarelo")
        self.verde = QtWidgets.QRadioButton(self.centralwidget)
        self.verde.setGeometry(QtCore.QRect(190, 150, 121, 17))
        self.verde.setStyleSheet("color: rgb(0, 85, 0);")
        self.verde.setObjectName("verde")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Escolha uma cor"))
        self.cor_escolhida.setText(_translate("MainWindow", "Cor Escolhida: "))
        self.checar.setText(_translate("MainWindow", "Checar"))
        self.vermelho.setText(_translate("MainWindow", "Vermelho"))
        self.amarelo.setText(_translate("MainWindow", "Amarelo"))
        self.verde.setText(_translate("MainWindow", "Verde"))

if __name__ == "__main__":
        import sys

        def cor():
                if ui.verde.isChecked():
                       opc = "verde selecionado"
                elif ui.vermelho.isChecked():
                        opc = "vermelho selecionado"
                elif ui.amarelo.isChecked():
                        opc = "amarelo selecionado"
                else:
                        opc = ""
                
                ui.cor_escolhida.setText(opc)

        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        ui.checar.clicked.connect(cor)
        MainWindow.show()
        sys.exit(app.exec_())